version: 2
jobs:
  lint:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/qgis-stac-browser
    resource_class: small
    steps:
    - checkout
    - run:
        name: Install flake8
        command: sudo pip install flake8==3.7.7
    - run:
        name: Run lint
        command: make lint
  build:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/qgis-stac-browser
    resource_class: small
    steps:
    - checkout
    - run:
        name: Install pb_tool and PyQT5
        command: sudo pip install pb_tool pyqt5
    - run:
        name: Make plugin directory
        command: mkdir /home/circleci/plugin
    - run:
        name: Update pb_tool.cfg
        command: "sed -i -e 's/plugin_path:/plugin_path: \\/home\\/circleci\\/plugin/' pb_tool.cfg"
    - run:
        name: Deploy plugin and build zip
        command: make build
    - store_artifacts:
        path: ~/qgis-stac-browser/stac_browser.zip
        destination: stac_browser.zip
workflows:
  build:
    jobs:
    - lint
    - build
  version: 2
